spring.application.name=stecar-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/stecar
spring.datasource.username=postgres
spring.datasource.password=Jv123456@#

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

stecar.jwt.secret=${STECAR_JWT_SECRET}